---
title: "Public policy for fairness and efficiency"
linktitle: "4: Public policy for fairness and efficiency"
date: "2020-06-15"
start_date: "2020-06-15"
end_date: "2020-06-19"
menu:
  content:
    parent: Course content
    weight: 4
type: docs
bibliography: "../../static/bib/references.bib"
csl: "../../static/bib/chicago-fullnote-bibliography-no-bib.csl"
# slides: "04-slides"
output:
  blogdown::html_page:
    toc: true
---

## Readings

- <i class="fas fa-book"></i> Introduction and 3.1-3.11 in *Economy, Society, and Public Policy* [@core-espp]
- <i class="fab fa-youtube"></i> [The Veil of Ignorance](https://www.youtube.com/watch?v=A8GDEaJtbq4)
- <i class="fas fa-external-link-square-alt"></i> [The Fairness Principle: How the Veil of Ignorance Helps Test Fairness](https://fs.blog/2017/10/veil-ignorance/)
- <i class="fas fa-podcast"></i> Planet Money, ["Retraining Day,"](https://www.npr.org/sections/money/2017/01/27/512060753/episode-750-retraining-day) episode 750, January 27, 2017
- <i class="fas fa-podcast"></i> Planet Money, ["The Bottom of the Well,"](https://www.npr.org/sections/money/2015/07/22/425392169/episode-640-the-bottom-of-the-well) episode 640, July 22, 2015
- <i class="far fa-file-pdf"></i> Alberto Alesina and George-Marios Angeletos, "Fairness and Redistribution: US vs. Europe" [@AlesinaAngeletos:2005] 
    - [Download the PDF here](https://scholar.harvard.edu/files/alesina/files/fairness_and_redistribution.pdf), or access it on iCollege.
    - This one is *super mathy* in the middle. Use your grad school reading skills to dig deep into the introduction, conclusion, and theory sections and not worry so much about the math.


## Other useful resources

Links to other resources like YouTube videos, etc. will go here if needed.


## Slides

Slides will go here.


## Videos

Videos will go here.
