---
title: "The firm"
linktitle: "7–8: The firm"
date: "2020-06-29"
start_date: "2020-06-29"
end_date: "2020-07-03"
menu:
  content:
    parent: Course content
    weight: 7
type: docs
bibliography: "../../static/bib/references.bib"
csl: "../../static/bib/chicago-fullnote-bibliography-no-bib.csl"
# slides: "02-slides"
output:
  blogdown::html_page:
    toc: true
---

## Readings

- <i class="fas fa-book"></i> Introduction and 6.1-6.14 in *Economy, Society, and Public Policy* [@core-espp]
- <i class="fab fa-youtube"></i> CORE team, ["Richard Freeman: You can't outsource responsibility"](https://www.youtube.com/watch?v=2Zm5ZLMKhgQ)
- <i class="fab fa-youtube"></i> Marginal Revolution University, [Asymmetric Information and Used Cars](https://www.youtube.com/watch?v=sXPXpJ5vMnU)
- <i class="fab fa-youtube"></i> Marginal Revolution University, [Asymmetric Information and Health Insurance](https://www.youtube.com/watch?v=pUkRo9COd38)
- <i class="fab fa-youtube"></i> Marginal Revolution University, [Moral Hazard](https://www.youtube.com/watch?v=5v7TWKlYoN0)
- <i class="fab fa-youtube"></i> Marginal Revolution University, [Solutions to Moral Hazard](https://www.youtube.com/watch?v=6faL76QZ2AA)
- Look at these real-life examples of information asymmetries and principal-agent problems:
    - <i class="fas fa-external-link-square-alt"></i> Sam Dolnick, ["Air-Conditioners That Run When Nobody's Home,"](http://www.nytimes.com/2010/08/16/nyregion/16chill.html) New York Times, August 15, 2010
    - <i class="fas fa-external-link-square-alt"></i> Ceci Connolly, ["U.S. worker's case reveals how drug cartels get help from this side of border,"](http://www.washingtonpost.com/wp-dyn/content/article/2010/09/11/AR2010091105087.html) Washington Post, September 12, 2010
    - <i class="fas fa-external-link-square-alt"></i> Rob Ferguson, ["Ontario’s winter roads 'less safe' since privatization: auditor,"](https://www.thestar.com/news/canada/2015/04/29/ontarios-winter-roads-are-less-safe-since-privatization-auditor.html) The Star, April 29, 2015


## Other useful resources

Links to other resources like YouTube videos, etc. will go here if needed.


## Slides

Slides will go here.


## Videos

Videos will go here.
